# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
