# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory',
        ),
    ]
